apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      name: hello-demo
  template:
    metadata:
      labels:
        app: backend
        name: hello-demo
    spec:
      volumes:
        - name: application-props-volume
          configMap:
            name: application-props
      containers:
        - name: hello-demo
          imagePullPolicy: Never
          image: hello-demo
          volumeMounts:
            - mountPath: /etc/config
              name: application-props-volume
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: backend
    name: hello-demo
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
